# Generated by Django 4.2 on 2023-04-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commets',
            new_name='Comments',
        ),
    ]
